package task2_Try_Catch;

/**
 * Created by Byblik272 on 24/11/2015.
 */
public class Exception_In_Catch {
    public static void main(String[] args) {

    }
}
